name: Datasets

on:
  push:
    branches: [ "master" ]
    paths:
      - 'datasets/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'datasets/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r datasets/requirements.txt && pip install Pillow
      - run: ENV=test python3 datasets/mnist_dataset.py
      - name: Upload Dataset Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mnist_artifact
          path: tmp/*
          retention-days: 30
