# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildDataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r datasets/requirements.txt && pip install Pillow
      - run: ENV=test python3 datasets/mnist_dataset.py
      - name: Upload Dataset Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mnist_artifact
          path: tmp/*
          retention-days: 30
  runTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Download a test files artifact
      uses: actions/download-artifact@v4
      with:
        needs: buildDataset
        name: mnist_artifact
        path: tmp/
        
    - name: Test
      run: go test
